### ISSUE TITLE
Both Window Cover and Overlay Contents Doesn't Update on Color Scheme Change

### ISSUE THREAD

**Issue by DaniShalash** [divadretlaw/WindowKit#2] opened 2023-10-27 18:21 UTC
Hello,

First Thank you for the amazing solution you have provided.

### **Issue:**
I'm using this library in my project and I have found that once a window cover (or overlay) is presented, the content view will not change, and specifically what I'm struggling with is responding to light and dark modes on device.

### **How to reproduce:**
Present any view with a "Thick Material" for example using `.windowCover`, and the toggle between light and dark mode on your device, you'll notice the view is not responding to such changes.

I have tried to send the colorScheme to the windowCover content using an ObservableObject, and then send the preferredColorScheme on the content view, but it didn't work, even though the View received the change successfully.

### **Environment:**
Device: iPhone 13 Pro Max
OS: iOS 17
Minimum Deployment: iOS 15

**Comment by divadretlaw** [comment] 2023-10-28 14:02
Hi, thank you for bringing this to my attention. The issue is that the environment was only copied once, but updates to it were lost, therefore disabling any updates to the environment. E.g. color scheme updates.

I think I have found a solution to pass the environment from the calling view to the view in the window and the fix is included in `1.2.0`.

Please let me know if you still experience any issues when using the updated version.

**Closed as completed** 2023-11-20 22:09 UTC
